sonar.projectName=ecommerce
sonar.sourceEncoding=UTF-8
sonar.sources=apps,packages
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts,**/*.test.ts,**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=apps/*/tsconfig.json,packages/*/tsconfig.json
sonar.exclusions=**/node_modules/**,**/.next/**,**/.turbo/**,**/.vercel/**,**/generated/**,**/coverage/**,**/dist/**,**/build/**,**/out/**,**/*.tsbuildinfo
