grafana:
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
