# Dependencies
node_modules
.pnp
.pnp.js

# Testing
coverage
tests/

# Next.js
.next/
out/
build
dist/
.turbo
.vercel
generated
**/.next
**/.turbo
**/.vercel
**/coverage
**/build
**/dist
**/out
**/generated

# Misc
.DS_Store
*.pem
*.key
*.log
tmp/
SKILL.md
sonar-project.properties

# Debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*
bun-debug.log*

# Local env files
.env
.env*.local
.env.development
.env.test
.env.production

# Vercel
.vercel

# Typescript
*.tsbuildinfo

# IDE
.vscode
.idea

# Git
.git
.github
.gitignore
README.md
