apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce.configMapName" . }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
data:
  {{- range $name, $value := .Values.global.env }}
  {{ $name }}: {{ tpl (printf "%v" $value) $ | quote }}
  {{- end }}
