graph TD
	RPGS("//#check-tools") --> ETQY("___ROOT___")
	KEFT("@repo/api-client#build") --> PRBV("@repo/contracts#build")
	KEFT("@repo/api-client#build") --> CXPQ("@repo/types#build")
	KEFT("@repo/api-client#build") --> MLKN("@repo/typescript-config#build")
	ZHXY("@repo/api-client#check-types") --> OVTW("@repo/api-client#typecheck-deps")
	NDRI("@repo/api-client#db:generate") --> ETQY("___ROOT___")
	OVTW("@repo/api-client#typecheck-deps") --> WGGN("@repo/contracts#db:generate")
	OVTW("@repo/api-client#typecheck-deps") --> RDVF("@repo/contracts#typecheck-deps")
	OVTW("@repo/api-client#typecheck-deps") --> PVEJ("@repo/types#db:generate")
	OVTW("@repo/api-client#typecheck-deps") --> CHNJ("@repo/types#typecheck-deps")
	OVTW("@repo/api-client#typecheck-deps") --> SXVB("@repo/typescript-config#db:generate")
	OVTW("@repo/api-client#typecheck-deps") --> VVSC("@repo/typescript-config#typecheck-deps")
	PRBV("@repo/contracts#build") --> CXPQ("@repo/types#build")
	PRBV("@repo/contracts#build") --> MLKN("@repo/typescript-config#build")
	WAGD("@repo/contracts#check-types") --> RDVF("@repo/contracts#typecheck-deps")
	WGGN("@repo/contracts#db:generate") --> ETQY("___ROOT___")
	RDVF("@repo/contracts#typecheck-deps") --> PVEJ("@repo/types#db:generate")
	RDVF("@repo/contracts#typecheck-deps") --> CHNJ("@repo/types#typecheck-deps")
	RDVF("@repo/contracts#typecheck-deps") --> SXVB("@repo/typescript-config#db:generate")
	RDVF("@repo/contracts#typecheck-deps") --> VVSC("@repo/typescript-config#typecheck-deps")
	CQCF("@repo/hono-utils#check-types") --> NOOO("@repo/hono-utils#typecheck-deps")
	CKYN("@repo/hono-utils#db:generate") --> ETQY("___ROOT___")
	NOOO("@repo/hono-utils#typecheck-deps") --> PVEJ("@repo/types#db:generate")
	NOOO("@repo/hono-utils#typecheck-deps") --> CHNJ("@repo/types#typecheck-deps")
	NOOO("@repo/hono-utils#typecheck-deps") --> SXVB("@repo/typescript-config#db:generate")
	NOOO("@repo/hono-utils#typecheck-deps") --> VVSC("@repo/typescript-config#typecheck-deps")
	GPSL("@repo/kafka#check-types") --> QHDQ("@repo/kafka#typecheck-deps")
	JJLV("@repo/kafka#db:generate") --> ETQY("___ROOT___")
	QHDQ("@repo/kafka#typecheck-deps") --> SXVB("@repo/typescript-config#db:generate")
	QHDQ("@repo/kafka#typecheck-deps") --> VVSC("@repo/typescript-config#typecheck-deps")
	QLYZ("@repo/order-db#check-types") --> ORSQ("@repo/order-db#typecheck-deps")
	JKAP("@repo/order-db#db:generate") --> ETQY("___ROOT___")
	ORSQ("@repo/order-db#typecheck-deps") --> SXVB("@repo/typescript-config#db:generate")
	ORSQ("@repo/order-db#typecheck-deps") --> VVSC("@repo/typescript-config#typecheck-deps")
	GEEP("@repo/product-db#check-types") --> WOVD("@repo/product-db#db:generate")
	GEEP("@repo/product-db#check-types") --> SMBB("@repo/product-db#typecheck-deps")
	WOVD("@repo/product-db#db:generate") --> ETQY("___ROOT___")
	SMBB("@repo/product-db#typecheck-deps") --> SXVB("@repo/typescript-config#db:generate")
	SMBB("@repo/product-db#typecheck-deps") --> VVSC("@repo/typescript-config#typecheck-deps")
	CXPQ("@repo/types#build") --> MLKN("@repo/typescript-config#build")
	EADY("@repo/types#check-types") --> CHNJ("@repo/types#typecheck-deps")
	PVEJ("@repo/types#db:generate") --> ETQY("___ROOT___")
	CHNJ("@repo/types#typecheck-deps") --> SXVB("@repo/typescript-config#db:generate")
	CHNJ("@repo/types#typecheck-deps") --> VVSC("@repo/typescript-config#typecheck-deps")
	MLKN("@repo/typescript-config#build") --> ETQY("___ROOT___")
	SXVB("@repo/typescript-config#db:generate") --> ETQY("___ROOT___")
	VVSC("@repo/typescript-config#typecheck-deps") --> ETQY("___ROOT___")
	NQCT("admin#build") --> KEFT("@repo/api-client#build")
	NQCT("admin#build") --> CXPQ("@repo/types#build")
	NQCT("admin#build") --> MLKN("@repo/typescript-config#build")
	QGIL("admin#check-types") --> QQOZ("admin#typecheck-deps")
	QQOZ("admin#typecheck-deps") --> NDRI("@repo/api-client#db:generate")
	QQOZ("admin#typecheck-deps") --> OVTW("@repo/api-client#typecheck-deps")
	QQOZ("admin#typecheck-deps") --> PVEJ("@repo/types#db:generate")
	QQOZ("admin#typecheck-deps") --> CHNJ("@repo/types#typecheck-deps")
	QQOZ("admin#typecheck-deps") --> SXVB("@repo/typescript-config#db:generate")
	QQOZ("admin#typecheck-deps") --> VVSC("@repo/typescript-config#typecheck-deps")
	SWWV("client#build") --> KEFT("@repo/api-client#build")
	SWWV("client#build") --> CXPQ("@repo/types#build")
	SWWV("client#build") --> MLKN("@repo/typescript-config#build")
	CTBB("client#check-types") --> KJRI("client#typecheck-deps")
	KJRI("client#typecheck-deps") --> NDRI("@repo/api-client#db:generate")
	KJRI("client#typecheck-deps") --> OVTW("@repo/api-client#typecheck-deps")
	KJRI("client#typecheck-deps") --> PVEJ("@repo/types#db:generate")
	KJRI("client#typecheck-deps") --> CHNJ("@repo/types#typecheck-deps")
	KJRI("client#typecheck-deps") --> SXVB("@repo/typescript-config#db:generate")
	KJRI("client#typecheck-deps") --> VVSC("@repo/typescript-config#typecheck-deps")
	HUDV("order-service#check-types") --> LWJS("order-service#typecheck-deps")
	LWJS("order-service#typecheck-deps") --> WGGN("@repo/contracts#db:generate")
	LWJS("order-service#typecheck-deps") --> RDVF("@repo/contracts#typecheck-deps")
	LWJS("order-service#typecheck-deps") --> CKYN("@repo/hono-utils#db:generate")
	LWJS("order-service#typecheck-deps") --> NOOO("@repo/hono-utils#typecheck-deps")
	LWJS("order-service#typecheck-deps") --> JJLV("@repo/kafka#db:generate")
	LWJS("order-service#typecheck-deps") --> QHDQ("@repo/kafka#typecheck-deps")
	LWJS("order-service#typecheck-deps") --> JKAP("@repo/order-db#db:generate")
	LWJS("order-service#typecheck-deps") --> ORSQ("@repo/order-db#typecheck-deps")
	LWJS("order-service#typecheck-deps") --> PVEJ("@repo/types#db:generate")
	LWJS("order-service#typecheck-deps") --> CHNJ("@repo/types#typecheck-deps")
	LWJS("order-service#typecheck-deps") --> SXVB("@repo/typescript-config#db:generate")
	LWJS("order-service#typecheck-deps") --> VVSC("@repo/typescript-config#typecheck-deps")
	EBJD("payment-service#check-types") --> GSLJ("payment-service#typecheck-deps")
	GSLJ("payment-service#typecheck-deps") --> NDRI("@repo/api-client#db:generate")
	GSLJ("payment-service#typecheck-deps") --> OVTW("@repo/api-client#typecheck-deps")
	GSLJ("payment-service#typecheck-deps") --> WGGN("@repo/contracts#db:generate")
	GSLJ("payment-service#typecheck-deps") --> RDVF("@repo/contracts#typecheck-deps")
	GSLJ("payment-service#typecheck-deps") --> CKYN("@repo/hono-utils#db:generate")
	GSLJ("payment-service#typecheck-deps") --> NOOO("@repo/hono-utils#typecheck-deps")
	GSLJ("payment-service#typecheck-deps") --> JJLV("@repo/kafka#db:generate")
	GSLJ("payment-service#typecheck-deps") --> QHDQ("@repo/kafka#typecheck-deps")
	GSLJ("payment-service#typecheck-deps") --> PVEJ("@repo/types#db:generate")
	GSLJ("payment-service#typecheck-deps") --> CHNJ("@repo/types#typecheck-deps")
	GSLJ("payment-service#typecheck-deps") --> SXVB("@repo/typescript-config#db:generate")
	GSLJ("payment-service#typecheck-deps") --> VVSC("@repo/typescript-config#typecheck-deps")
	QLDY("product-service#check-types") --> AYAF("product-service#typecheck-deps")
	AYAF("product-service#typecheck-deps") --> WGGN("@repo/contracts#db:generate")
	AYAF("product-service#typecheck-deps") --> RDVF("@repo/contracts#typecheck-deps")
	AYAF("product-service#typecheck-deps") --> CKYN("@repo/hono-utils#db:generate")
	AYAF("product-service#typecheck-deps") --> NOOO("@repo/hono-utils#typecheck-deps")
	AYAF("product-service#typecheck-deps") --> JJLV("@repo/kafka#db:generate")
	AYAF("product-service#typecheck-deps") --> QHDQ("@repo/kafka#typecheck-deps")
	AYAF("product-service#typecheck-deps") --> WOVD("@repo/product-db#db:generate")
	AYAF("product-service#typecheck-deps") --> SMBB("@repo/product-db#typecheck-deps")
	AYAF("product-service#typecheck-deps") --> PVEJ("@repo/types#db:generate")
	AYAF("product-service#typecheck-deps") --> CHNJ("@repo/types#typecheck-deps")
	AYAF("product-service#typecheck-deps") --> SXVB("@repo/typescript-config#db:generate")
	AYAF("product-service#typecheck-deps") --> VVSC("@repo/typescript-config#typecheck-deps")
