graph TD
	RPGS("@repo/api-client#build") --> ETQY("@repo/contracts#build")
	RPGS("@repo/api-client#build") --> KEFT("@repo/types#build")
	RPGS("@repo/api-client#build") --> PRBV("@repo/typescript-config#build")
	CXPQ("@repo/api-client#check-types") --> MLKN("@repo/contracts#check-types")
	CXPQ("@repo/api-client#check-types") --> ZHXY("@repo/types#check-types")
	CXPQ("@repo/api-client#check-types") --> OVTW("@repo/typescript-config#check-types")
	ETQY("@repo/contracts#build") --> KEFT("@repo/types#build")
	ETQY("@repo/contracts#build") --> PRBV("@repo/typescript-config#build")
	MLKN("@repo/contracts#check-types") --> ZHXY("@repo/types#check-types")
	MLKN("@repo/contracts#check-types") --> OVTW("@repo/typescript-config#check-types")
	NDRI("@repo/hono-utils#build") --> KEFT("@repo/types#build")
	NDRI("@repo/hono-utils#build") --> PRBV("@repo/typescript-config#build")
	WGGN("@repo/hono-utils#check-types") --> ZHXY("@repo/types#check-types")
	WGGN("@repo/hono-utils#check-types") --> OVTW("@repo/typescript-config#check-types")
	RDVF("@repo/kafka#build") --> PRBV("@repo/typescript-config#build")
	PVEJ("@repo/kafka#check-types") --> OVTW("@repo/typescript-config#check-types")
	CHNJ("@repo/order-db#build") --> PRBV("@repo/typescript-config#build")
	SXVB("@repo/order-db#check-types") --> OVTW("@repo/typescript-config#check-types")
	VVSC("@repo/product-db#build") --> PRBV("@repo/typescript-config#build")
	WAGD("@repo/product-db#check-types") --> CQCF("@repo/product-db#db:generate")
	WAGD("@repo/product-db#check-types") --> OVTW("@repo/typescript-config#check-types")
	CQCF("@repo/product-db#db:generate") --> NOOO("___ROOT___")
	KEFT("@repo/types#build") --> PRBV("@repo/typescript-config#build")
	ZHXY("@repo/types#check-types") --> OVTW("@repo/typescript-config#check-types")
	PRBV("@repo/typescript-config#build") --> NOOO("___ROOT___")
	OVTW("@repo/typescript-config#check-types") --> NOOO("___ROOT___")
	CKYN("admin#build") --> RPGS("@repo/api-client#build")
	CKYN("admin#build") --> KEFT("@repo/types#build")
	CKYN("admin#build") --> PRBV("@repo/typescript-config#build")
	GPSL("admin#check-types") --> CXPQ("@repo/api-client#check-types")
	GPSL("admin#check-types") --> ZHXY("@repo/types#check-types")
	GPSL("admin#check-types") --> OVTW("@repo/typescript-config#check-types")
	QHDQ("client#build") --> RPGS("@repo/api-client#build")
	QHDQ("client#build") --> KEFT("@repo/types#build")
	QHDQ("client#build") --> PRBV("@repo/typescript-config#build")
	JJLV("client#check-types") --> CXPQ("@repo/api-client#check-types")
	JJLV("client#check-types") --> ZHXY("@repo/types#check-types")
	JJLV("client#check-types") --> OVTW("@repo/typescript-config#check-types")
	QLYZ("order-service#build") --> ETQY("@repo/contracts#build")
	QLYZ("order-service#build") --> NDRI("@repo/hono-utils#build")
	QLYZ("order-service#build") --> RDVF("@repo/kafka#build")
	QLYZ("order-service#build") --> CHNJ("@repo/order-db#build")
	QLYZ("order-service#build") --> KEFT("@repo/types#build")
	QLYZ("order-service#build") --> PRBV("@repo/typescript-config#build")
	ORSQ("order-service#check-types") --> MLKN("@repo/contracts#check-types")
	ORSQ("order-service#check-types") --> WGGN("@repo/hono-utils#check-types")
	ORSQ("order-service#check-types") --> PVEJ("@repo/kafka#check-types")
	ORSQ("order-service#check-types") --> SXVB("@repo/order-db#check-types")
	ORSQ("order-service#check-types") --> ZHXY("@repo/types#check-types")
	ORSQ("order-service#check-types") --> OVTW("@repo/typescript-config#check-types")
	JKAP("payment-service#build") --> RPGS("@repo/api-client#build")
	JKAP("payment-service#build") --> ETQY("@repo/contracts#build")
	JKAP("payment-service#build") --> NDRI("@repo/hono-utils#build")
	JKAP("payment-service#build") --> RDVF("@repo/kafka#build")
	JKAP("payment-service#build") --> KEFT("@repo/types#build")
	JKAP("payment-service#build") --> PRBV("@repo/typescript-config#build")
	GEEP("payment-service#check-types") --> CXPQ("@repo/api-client#check-types")
	GEEP("payment-service#check-types") --> MLKN("@repo/contracts#check-types")
	GEEP("payment-service#check-types") --> WGGN("@repo/hono-utils#check-types")
	GEEP("payment-service#check-types") --> PVEJ("@repo/kafka#check-types")
	GEEP("payment-service#check-types") --> ZHXY("@repo/types#check-types")
	GEEP("payment-service#check-types") --> OVTW("@repo/typescript-config#check-types")
	WOVD("product-service#build") --> ETQY("@repo/contracts#build")
	WOVD("product-service#build") --> NDRI("@repo/hono-utils#build")
	WOVD("product-service#build") --> RDVF("@repo/kafka#build")
	WOVD("product-service#build") --> VVSC("@repo/product-db#build")
	WOVD("product-service#build") --> KEFT("@repo/types#build")
	WOVD("product-service#build") --> PRBV("@repo/typescript-config#build")
	SMBB("product-service#check-types") --> MLKN("@repo/contracts#check-types")
	SMBB("product-service#check-types") --> WGGN("@repo/hono-utils#check-types")
	SMBB("product-service#check-types") --> PVEJ("@repo/kafka#check-types")
	SMBB("product-service#check-types") --> WAGD("@repo/product-db#check-types")
	SMBB("product-service#check-types") --> ZHXY("@repo/types#check-types")
	SMBB("product-service#check-types") --> OVTW("@repo/typescript-config#check-types")
